#coding=utf-8
"""
Django settings for cmdb project.

Generated by 'django-admin startproject' using Django 1.8.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""
import djcelery
from datetime import timedelta
from celery.schedules import crontab
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '8c6at)m_%6(f3f$9h3-zz)dl24!jou+ich5e*b&7e)yg+v5rfn'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cmdb',
    'server',
    'api',
    'zabbix',
    'clry',
    'djcelery',
    'log',
    'Users',
    'user_manager',
    'tech_stack',
    'testenv',
    'im_one_server',
    'mysql_submeter',
    'celeryadmin',
    'mysql_submeter.tasks',
    'domain',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    # 'corsheaders.middleware.CorsMiddleware',
)

ROOT_URLCONF = 'cmdb.urls'
AUTH_USER_MODEL = 'Users.UserProfile'
LOGIN_URL = '/login/'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# TEMPLATE_DIRS = (os.path.join(BASE_DIR, 'templates'),)

WSGI_APPLICATION = 'cmdb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#    }
#}

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'cmdb',
        'USER': 'root',
        'PASSWORD': 'Fuliao10086',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/


STATIC_URL = '/static/'
STATIC_ROOT= os.path.join(BASE_DIR,'statics/')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
# STATICFILES_DIRS = (
#     os.path.join(BASE_DIR,'static/')
# )

djcelery.setup_loader()

CELERY_TIMEZONE = TIME_ZONE
CELERYBEAT_SCHEDULER = 'djcelery.schedulers.DatabaseScheduler'
# CELERYD_FORCE_EXECV = True    # 有些情况下可以防止死锁
# CELERYD_MAX_TASKS_PER_CHILD = 200    # 每个worker最多执行完200个任务就会被销毁，可防止内存泄露
BROKER_URL = 'redis://127.0.0.1:7379/0'
# CELERY_RESULT_BACKEND='djcelery.backends.database:DatabaseBackend'
# CELERYBEAT_SCHEDULER = "django_celery_beat.schedulers.DatabaseScheduler"
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['pickle', 'json', 'msgpack', 'yaml']
CELERY_ENABLE_UTC = True
CELERYD_LOG_FILE = BASE_DIR + "/logs/celery.log"         # log路径
CELERYBEAT_LOG_FILE = BASE_DIR + "/logs/beat.log"     # beat log路径

APPEND_SLASH = False

CELERYBEAT_SCHEDULE = {
        'perminute': {
            'task': 'zabbix.tasks.zabbix_cron',
            'schedule': timedelta(seconds=600),
        },
        'perhour': {
            'task': 'zabbix.tasks.zabbix_url_cron',
            # 'schedule': crontab(hour="*",minute=30),
            'schedule': timedelta(seconds=3600),
        },
}

#jenkins
JENKINS_URL = 'http://testdb.jenkins.ipaychat.com:8090'
JENKINS_WORKSPASE = '/root/.jenkins/jobs'
JENKINS_USER = 'testdb'
JENKINS_PASSWORD = 'fuliaotest'

#ldap
LDAP_SERVER = '10.0.20.165'
LDAP_SCBASE = 'ou=fuliao,dc=example,dc=com'
LDAP_ADMIN = 'uid=wuliang@ipaychat.com,ou=ops,ou=fuliao,dc=example,dc=com'
LDAP_ADMIN_PASSWORD = 'xiongqian0610'
