# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-08-06 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DbSyncRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_dbhost', models.CharField(default=b'', max_length=512, verbose_name=b'\xe8\xa2\xab\xe5\x90\x8c\xe6\xad\xa5\xe6\x95\xb0\xe6\x8d\xae\xe5\xba\x93host')),
                ('from_dbport', models.IntegerField(default=b'', max_length=512, verbose_name=b'\xe8\xa2\xab\xe5\x90\x8c\xe6\xad\xa5\xe6\x95\xb0\xe6\x8d\xae\xe5\xba\x93port')),
                ('to_dbhost', models.CharField(default=b'', max_length=512, verbose_name=b'\xe5\x90\x8c\xe6\xad\xa5\xe6\x95\xb0\xe6\x8d\xae\xe5\xba\x93port')),
                ('to_dbport', models.IntegerField(default=b'', max_length=512, verbose_name=b'\xe5\x90\x8c\xe6\xad\xa5\xe6\x95\xb0\xe6\x8d\xae\xe5\xba\x93port')),
                ('from_database', models.CharField(default=b'', max_length=512, verbose_name=b'\xe8\xa2\xab\xe5\x90\x8c\xe6\xad\xa5\xe6\x95\xb0\xe6\x8d\xae\xe5\xba\x93\xe5\x90\x8d\xe7\xa7\xb0')),
                ('to_database', models.CharField(default=b'', max_length=512, verbose_name=b'\xe5\x90\x8c\xe6\xad\xa5\xe6\x95\xb0\xe6\x8d\xae\xe5\xba\x93\xe5\x90\x8d\xe7\xa7\xb0')),
                ('tables', models.CharField(default=b'', max_length=512, verbose_name=b'\xe8\xa2\xab\xe5\x90\x8c\xe6\xad\xa5\xe6\x95\xb0\xe6\x8d\xae\xe5\xba\x93\xe8\xa1\xa8\xef\xbc\x8c\xe7\xa9\xba\xe6\xa0\xbc\xe5\x88\x86\xe9\x9a\x94')),
                ('pattern', models.CharField(choices=[(b'test', '\u6d4b\u8bd5\u73af\u5883\u540c\u6b65'), (b'product', '\u7ebf\u4e0a\u73af\u5883\u540c\u6b65'), (b'testtoproduct', '\u6d4b\u8bd5\u540c\u6b65\u7ebf\u4e0a'), (b'producttotest', '\u7ebf\u4e0a\u540c\u6b65\u6d4b\u8bd5')], default=b'test', max_length=512, verbose_name=b'\xe5\x90\x8c\xe6\xad\xa5\xe6\xa8\xa1\xe5\xbc\x8f')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
