# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2020-08-31 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysql_submeter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbsyncrecord',
            name='crontab_task',
            field=models.CharField(default=b'', max_length=512, verbose_name=b'\xe5\xae\x9a\xe6\x97\xb6\xe6\x89\xa7\xe8\xa1\x8c'),
        ),
        migrations.AddField(
            model_name='dbsyncrecord',
            name='operator',
            field=models.CharField(default=b'', max_length=512, verbose_name=b'\xe6\x93\x8d\xe4\xbd\x9c\xe4\xba\xba'),
        ),
    ]
