# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-07-19 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tech_stack_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='\u6280\u672f\u6808\u540d\u79f0')),
                ('download_url', models.CharField(max_length=512, verbose_name='\u4e0b\u8f7d\u94fe\u63a5')),
                ('info', models.CharField(max_length=512, null=True, verbose_name='\u63cf\u8ff0')),
            ],
        ),
    ]
