# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-09-03 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomainInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=128, verbose_name='\u540d\u79f0')),
                ('start_date', models.CharField(blank=True, max_length=128, verbose_name='\u5f00\u59cb\u65e5\u671f')),
                ('end_date', models.CharField(blank=True, max_length=128, verbose_name='\u8fc7\u671f\u65e5\u671f')),
                ('usage', models.CharField(max_length=512, verbose_name='\u57df\u540d\u4f5c\u7528')),
                ('ssl_domain_name', models.CharField(max_length=512, verbose_name='\u8bc1\u4e66\u68c0\u6d4b\u57df\u540d')),
                ('ssl_start_date', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u8bc1\u4e66\u5f00\u59cb\u65e5\u671f')),
                ('ssl_end_date', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u8bc1\u4e66\u5f00\u59cb\u65e5\u671f')),
            ],
        ),
    ]
