# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2019-07-19 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test_env_history',
            fields=[
                ('env_name', models.CharField(max_length=128, null=True, verbose_name='\u6d4b\u8bd5\u73af\u5883\u540d')),
                ('project_name', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='\u9879\u76ee\u540d')),
                ('project_leader', models.CharField(max_length=128, verbose_name='\u9879\u76ee\u7ecf\u7406')),
                ('project_developer', models.CharField(max_length=512, null=True, verbose_name='\u5f00\u53d1\u4eba\u5458')),
                ('spend_time', models.IntegerField(max_length=8, null=True, verbose_name='\u5f00\u53d1\u82b1\u8d39\u65f6\u95f4')),
                ('gmt_created', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='test_env_info',
            fields=[
                ('env_name', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='\u6d4b\u8bd5\u73af\u5883\u540d')),
                ('project_name', models.CharField(max_length=128, null=True, verbose_name='\u9879\u76ee\u540d')),
                ('project_leader', models.CharField(max_length=128, null=True, verbose_name='\u9879\u76ee\u7ecf\u7406')),
                ('project_developer', models.CharField(max_length=512, null=True, verbose_name='\u5f00\u53d1\u4eba\u5458')),
                ('start_time', models.DateTimeField(null=True, verbose_name='\u7533\u8bf7\u65f6\u95f4')),
                ('end_time', models.DateTimeField(null=True, verbose_name='\u7ed3\u675f\u65f6\u95f4')),
                ('status', models.IntegerField(choices=[(b'0', 'use'), (b'1', 'not_use')], default=1, verbose_name='\u4f7f\u7528or\u6ca1\u5728\u4f7f\u7528')),
                ('java_jenkins_id', models.IntegerField(max_length=128, null=True, verbose_name='java\u73af\u5883\u7684\u5f53\u524d\u6784\u5efaid')),
                ('im_jenkins_id', models.IntegerField(max_length=128, null=True, verbose_name='im\u73af\u5883\u7684\u5f53\u524d\u6784\u5efaid')),
                ('db_jenkins_id', models.IntegerField(max_length=128, null=True, verbose_name='db\u73af\u5883\u7684\u5f53\u524d\u6784\u5efaid')),
            ],
        ),
    ]
