# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2020-08-31 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20200603_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='service_app',
        ),
        migrations.AddField(
            model_name='server',
            name='server_app',
            field=models.IntegerField(choices=[(b'0', 'fuliao'), (b'1', 'midao')], default=0, verbose_name='\u670d\u52a1\u5668\u5f52\u5c5eapp'),
        ),
        migrations.AddField(
            model_name='server',
            name='sn',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='sn'),
        ),
    ]
